services:
  telegram-bot:
    build: .
    container_name: withlist_tg_bot
    restart: unless-stopped
    volumes:
      - ./bot_data:/app/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}

